### ISSUE TITLE
IO scheme encoding support

### ISSUE THREAD

**Issue by eloukas** [chakki-works/seqeval#70]
**IO scheme encoding**
---------
Hi, hope you are doing well. 
I'd like to ask you if you could incorporate simple _IO_ scheme encoding in seqeval.

Thank you for this awesome library.

**Comment by Hironsan** [comment]
Hello,

I don't have a plan to implement IO scheme because it is defective in that it can't represent two entities next to each other.

**Comment by wzkariampuzha** [comment]
Hi! I wanted to reach out because even though the IO scheme cannot identify identical entities next to each other, it is not "defective" as it has applications in production ML models which still need performance evaluations. I am building a production model now, and we are switching from IOB2 to IO for [better performance](https://www.sciencedirect.com/science/article/pii/S1110866520301596) on our task so it would be fantastic if you could add the IO option. Thank you!
